### PR TITLE
feat: List

### PR DESCRIPTION
**Pull request by gvhuyssteen**
Screenshot 2022-08-31 at 11 08 26
Screenshot 2022-08-31 at 11 08 31

### CODE REVIEW

**Comment by mathiasjakobsen** [comment]
@gvhuyssteen when would we not use a table in this case? 🤔

**Comment by gvhuyssteen** [comment]
> @gvhuyssteen when would we not use a table in this case? 🤔

@mathiasjakobsen 
In figma, there is a difference between Lists and Tables.
This component is the "List"

**Comment by mathiasjakobsen** [comment]
@gvhuyssteen maybe from a design point of view, I guess. But I only see the headings as the difference. I'm not sure about the use case - but we'll see.

**Review by mathiasjakobsen — APPROVED** [review]

**Review by mathiasjakobsen — CHANGES_REQUESTED** [review]
`<ListItem>` and `<ListItemCol>` still doesn't concat the className into the `classes` - hence won't work when used.

**Review by mathiasjakobsen — APPROVED** [review]

**Review by Bartal — APPROVED** [review]

**Pull request merged**
