### PR TITLE
Extra/button with icon

### PR DESCRIPTION
**Pull request by gvhuyssteen**

### CODE REVIEW

**Review by mathiasjakobsen — APPROVED** [review]

**Review by mathiasjakobsen — CHANGES_REQUESTED** [review]
The conventions are `fas`, `far` and `fal` ⭐

**Comment by gvhuyssteen** [comment]
> The conventions are `fas`, `far` and `fal` ⭐

I've spent so much time trying to figure out why regular (far) is not loading.
Regular is only available in PRO.
https://fontawesome.com/docs/web/add-icons/how-to#basics

**Comment by mathiasjakobsen** [comment]
@gvhuyssteen yup, and we have a licens 🥳  Check out the .npmrc in Voice Finder project.

**Comment by gvhuyssteen** [comment]
image

**Comment by gvhuyssteen** [comment]
image

**Review by mathiasjakobsen — APPROVED** [review]
Approved, but with one things that I'll leave for you to decide. Either the props should accept i.e. `icon={['fas', 'user']}` or `icon={['solid', 'user']}`. I'm happy with the latter, but just FYI all existing references are using the first.

**Review by mathiasjakobsen — APPROVED** [review]

**Pull request merged**
