### PR TITLE
feat: Chips

### PR DESCRIPTION
**Pull request by gvhuyssteen**
image

### CODE REVIEW

**Comment by gvhuyssteen** [comment]
feature: chips.
not
fish and chips.

**Review by mathiasjakobsen — COMMENTED** [review]
Looks good - but, is there a reason why we don't have a background color on the chip? Isn't that the purpose - or? 🤔

**Comment by gvhuyssteen** [comment]
@mathiasjakobsen 

image

**Comment by mathiasjakobsen** [comment]
@gvhuyssteen in that case, it makes sense. But then the component need to accept a `className` prop, which will be merged into the classes.

**Comment by gvhuyssteen** [comment]
@mathiasjakobsen 

Done

image

**Review by mathiasjakobsen — APPROVED** [review]

**Pull request merged**
